# fly.toml app configuration file generated for japi-reloaded on 2024-04-11T12:14:43-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'japi-reloaded'
primary_region = 'ewr'

[build]
  [build.args]
    GO_VERSION = '1.22.2'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
